#Use of Random Module
import random
print()
print('----- Guess the Random Number Generated by the computer -----')
print('Total Attempts = 5')
W = 0
for j in range(3):
    print(f'\t\t\tWinner in {W} / 3 Games')
    print(f'\t\t\tGame Number - {j+1}')
    attempt = 5
    random_number = random.randint(0,50)
    for i in range(5):
        user_input = int(input("Enter Number Between '0' to '50' only :"))

        if user_input == random_number:
            print('----------------------------------------------------------------------------')
            print('\n\t\t\tHurrrry, You won! :)\n')
            print('----------------------------------------------------------------------------')
            W+=1
            break
        else:
            if attempt == 1:
                print('------------------------------------------------------------------------------------------------------')
                print('\n\t\t\tAll Chances are Finished, Better Luck Next Time :(')
                print(f'\t\t\tCorrect Answer : {random_number}\n')
                print('------------------------------------------------------------------------------------------------------')
            else:
                print(f'\t\t** WRONG ** {attempt-1} left.')
                if(random_number < user_input):
                    print('\t\tHINT : Try Lower Number')
                else:
                    print('\t\tHINT : Try Bigger number')
                attempt -= 1
                continue
print('------------------------------------------------------------------------------------------------------')
print(f'\t\t\tYour Score is {W} / 3 Games')
if W>=2:
    print('\t\t\tYou are Magical')
    print('\t\t\tYou Won This Game')
    print('------------------------------------------------------------------------------------------------------')
else:
    print('\t\t\tYou Lost')
    print('\t\t\tBetter Luck Next Time')
    print('------------------------------------------------------------------------------------------------------')

